#ifndef CLOTHSIMLIB_GLOBAL_H
#define CLOTHSIMLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLOTHSIMLIB_LIBRARY)
#  define CLOTHSIMLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLOTHSIMLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLOTHSIMLIB_GLOBAL_H
